# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-21 06:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('note_id', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('note', models.TextField()),
            ],
        ),
    ]
